apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: __SERVICE_NAME__-__ENVIRONMENT__-0__ENV_INSTANCE__
  namespace: flux-config
  labels:
    backstage.io/kubernetes-id: __SERVICE_NAME__
    backstage.io/kubernetes-team: __TEAM_NAME__
spec:
  imageRepositoryRef:
    name: __SERVICE_NAME__
  policy:
    semver:
      range: '>=0.1.0'