apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: __SERVICE_NAME__-deploy
  namespace: flux-config
  labels:
    backstage.io/kubernetes-id: __SERVICE_NAME__
    backstage.io/kubernetes-team: __TEAM_NAME__
spec:
  dependsOn:
    - name: __SERVICE_NAME__-__DEPENDS_ON__
      namespace: flux-config
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: flux-config
  path: ./services/__PROGRAMME_NAME__/__TEAM_NAME__/__SERVICE_NAME__/deploy/${ENVIRONMENT}/${ENVIRONMENT_ID}
  interval: 5m
  timeout: 3m
  prune: true
  wait: true
  force: true
  postBuild:
    substitute:
      SERVICE_NAME: "__SERVICE_NAME__"
      TEAM_NAMESPACE: ${TEAM_NAMESPACE}
      TEAM_NAME: ${TEAM_NAME}
      APPCONFIG_NAME: ${APPCONFIG_NAME}
      APPCONFIG_MI_CLIENTID: ${APPCONFIG_MI_CLIENTID}
    substituteFrom:
      - kind: ConfigMap
        name: adp-platform-vars
      - kind: ConfigMap
        name: "__SERVICE_NAME__-mi-credential"