apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: __SERVICE_NAME__-infra
  namespace: flux-config
  labels:
    backstage.io/kubernetes-id: __SERVICE_NAME__
    backstage.io/kubernetes-team: __TEAM_NAME__
spec:
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: flux-config
  path: ./services/__PROGRAMME_NAME__/__TEAM_NAME__/__SERVICE_NAME__/infra/${ENVIRONMENT}/${ENVIRONMENT_ID}
  interval: 5m
  timeout: 3m
  prune: true
  wait: true
  force: true
  postBuild:
    substitute:
      SERVICE_NAME: "__SERVICE_NAME__"
      TEAM_RG: ${TEAM_RG}
      TEAM_NAMESPACE: ${TEAM_NAMESPACE}
      TEAM_NAME: ${TEAM_NAME}
      SERVICE_CODE: ${SERVICE_CODE}
    substituteFrom:
      - kind: ConfigMap
        name: adp-platform-vars