apiVersion: batch/v1
kind: Job
metadata:
  name: __SERVICE_NAME__-post-dbmigration
  namespace: __TEAM_NAME__
spec:
  template:
    spec:
      containers:
      - name: __SERVICE_NAME__-post-dbmigration
        image: ssvadpinfcr3401.azurecr.io/image/powershell-executor:424529 # {"$imagepolicy": "flux-config:powershell-executor-__ENVIRONMENT__-0__ENV_INSTANCE__"}
        env:
        - name: GIT_REPO_URL
          value: "https://github.com/DEFRA/adp-flux-services.git"
        - name: GIT_BRANCH
          value: "main"
        - name: SCRIPT_FILE_NAME
          value: "common/scripts/access-control/flexible-server/Grant-FlexibleServerDBAccess.ps1"
        - name: POSTGRES_HOST
          value: "${SHARED_POSTGRES_SERVER_01}.postgres.database.azure.com"
        - name: POSTGRES_DATABASE
          value: ${POSTGRES_DB}
        - name: SERVICE_MI_NAME
          value: ${TEAM_MI_PREFIX}-${SERVICE_NAME}
        - name: TEAM_MI_SUBSCRIPTION_ID
          value: ${SUBSCRIPTION_ID}
        - name: SUBSCRIPTION_NAME
          value: ${SUBSCRIPTION_NAME}
        - name: PG_WRITER_AD_GROUP
          value: ${PG_WRITER_AD_GROUP}
        - name: PG_READER_AD_GROUP
          value: ${PG_READER_AD_GROUP}
        - name: DB_MIGRATION_VERSION
          value: "__VERSION__" # {"$imagepolicy": "flux-config:__SERVICE_NAME__-dbmigration-__ENVIRONMENT__-0__ENV_INSTANCE__:tag"}
